package sz.susan.AM.client;

import oracle.jbo.client.remote.ApplicationModuleImpl;

import sz.susan.AM.common.transAM;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 19 16:55:39 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class transAMClient extends ApplicationModuleImpl implements transAM {
    /**
     * This is the default constructor (do not remove).
     */
    public transAMClient() {
    }

    public Integer getInvokeCount(Integer id) {
        Object _ret = this.riInvokeExportedMethod(this,"getInvokeCount",new String [] {"java.lang.Integer"},new Object[] {id});
        return (Integer)_ret;
    }


    public void SetViewCriteria() {
        Object _ret = this.riInvokeExportedMethod(this,"SetViewCriteria",null,null);
        return;
    }

    public void initService() {
        Object _ret = this.riInvokeExportedMethod(this,"initService",null,null);
        return;
    }

    public void initTrans() {
        Object _ret = this.riInvokeExportedMethod(this,"initTrans",null,null);
        return;
    }
}
