package sz.susan.AM.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 19 16:55:39 CST 2013
// ---------------------------------------------------------------------
public interface transAM extends ApplicationModule {
    void initTrans();

    void initService();

    void SetViewCriteria();
}
