package sz.susan.AM;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;


import oracle.jbo.server.ViewObjectImpl;

import sz.susan.AM.common.transAM;
import sz.susan.VO.NodeVOImpl;
import sz.susan.VO.NodeVORowImpl;
import sz.susan.VO.ServiceVOImpl;
import sz.susan.VO.ServiceVORowImpl;
import sz.susan.VO.trancationVOImpl;
import sz.susan.VO.trancationVORowImpl;
import sz.susan.util.SusanTreeNode;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 19 13:13:51 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class transAMImpl extends ApplicationModuleImpl implements transAM {
    /**
     * This is the default constructor (do not remove).
     */
    public transAMImpl() {
    }


    public SusanTreeNode generateTree(){
        return null;
        }
    public void initTrans(){
        trancationVOImpl transVo = (trancationVOImpl)gettrancationVO1();
        trancationVORowImpl transRow = (trancationVORowImpl)transVo.next();
        int totalTime = getTotalTime();
        System.out.println(totalTime + transRow.getId());
        Integer tt = new Integer(totalTime);
        transRow.setTotalTime(tt);
        }
    public int getTotalTime(){
        NodeVOImpl nodeVo = (NodeVOImpl)getNodeVO1();        
        System.out.println("");
        NodeVORowImpl nodeRow = null;
        int totalTime = 0;
        while(nodeVo.hasNext()){
            nodeRow = (NodeVORowImpl)nodeVo.next();
            totalTime = totalTime + nodeRow.getTime();
            }
        return totalTime;
        }
    
    public void SetViewCriteria(){
        trancationVOImpl transactionVO=(trancationVOImpl)gettrancationVO1();
        transactionVO.setApplyViewCriteriaName("trancationVOCriteriaByID");
        transactionVO.setNamedWhereClauseParam("tId",((trancationVORowImpl)transactionVO.getCurrentRow()).ID);
        transactionVO.executeQuery();
    }
    
    public int getExceptTotalTime(){
            NodeVOImpl nodevo = (NodeVOImpl)getNodeVO1();
            NodeVORowImpl nodeRow = null;
            int exceptTotalTime = 0;
            ServiceVOImpl serviceVO = (ServiceVOImpl)getServiceVO1();
            serviceVO.setApplyViewCriteriaName("ServiceVOCriteria");
            while( nodevo.hasNext()){
                nodeRow = (NodeVORowImpl)nodevo.next();
                serviceVO.setNamedWhereClauseParam("ServeID", nodeRow.getServiceId());
                serviceVO.executeQuery();
                exceptTotalTime=exceptTotalTime+ ((ServiceVORowImpl)serviceVO.next()).getTime();
            }
            return exceptTotalTime;
        }
    public void initService(){
        ServiceVOImpl serviceVO = (ServiceVOImpl)getServiceVO1();
        ServiceVORowImpl serviceRow = null;
        int count = 0;
        while((serviceRow = (ServiceVORowImpl)serviceVO.next()) != null){
            count = getInvokeCount(serviceRow.getId());
            serviceRow.setInvokeCount(count);
            }
        }
    public Integer getInvokeCount(Integer id){
        NodeVOImpl nodeVO = getNodeVO1();
        nodeVO.setApplyViewCriteriaName("InvokeCountCriteria");
        nodeVO.setNamedWhereClauseParam("serviceID", id);
        nodeVO.executeQuery();
        return new Integer(nodeVO.getRowCount());
        }
    /**
     * Container's getter for trancationVO1.
     * @return trancationVO1
     */
    public trancationVOImpl gettrancationVO1() {
        return (trancationVOImpl)findViewObject("trancationVO1");
    }

    /**
     * Container's getter for NodeVO1.
     * @return NodeVO1
     */
    public NodeVOImpl getNodeVO1() {
        return (NodeVOImpl)findViewObject("NodeVO1");
    }

    /**
     * Container's getter for transToNodeViewLink1.
     * @return transToNodeViewLink1
     */
    public ViewLinkImpl gettransToNodeViewLink1() {
        return (ViewLinkImpl)findViewLink("transToNodeViewLink1");
    }


    /**
     * Container's getter for Depth_One_VO2.
     * @return Depth_One_VO2
     */
    public ViewObjectImpl getDepth_One_VO2() {
        return (ViewObjectImpl)findViewObject("Depth_One_VO2");
    }

    /**
     * Container's getter for trancationVO2.
     * @return trancationVO2
     */
    public ViewObjectImpl gettrancationVO2() {
        return (ViewObjectImpl)findViewObject("trancationVO2");
    }


    /**
     * Container's getter for Depth_One_VO3.
     * @return Depth_One_VO3
     */
    public ViewObjectImpl getDepth_One_VO3() {
        return (ViewObjectImpl)findViewObject("Depth_One_VO3");
    }


    /**
     * Container's getter for ServiceVO1.
     * @return ServiceVO1
     */
    public ServiceVOImpl getServiceVO1() {
        return (ServiceVOImpl)findViewObject("ServiceVO1");
    }


    /**
     * Container's getter for FaliedServiceViewObj1.
     * @return FaliedServiceViewObj1
     */
    public ViewObjectImpl getFaliedServiceViewObj1() {
        return (ViewObjectImpl)findViewObject("FaliedServiceViewObj1");
    }

    /**
     * Container's getter for InvokeTimeViewObj1.
     * @return InvokeTimeViewObj1
     */
    public ViewObjectImpl getInvokeTimeViewObj1() {
        return (ViewObjectImpl)findViewObject("InvokeTimeViewObj1");
    }


    /**
     * Container's getter for CpuViewObj1.
     * @return CpuViewObj1
     */
    public ViewObjectImpl getCpuViewObj1() {
        return (ViewObjectImpl)findViewObject("CpuViewObj1");
    }


    /**
     * Container's getter for Depth_1_VO1.
     * @return Depth_1_VO1
     */
    public ViewObjectImpl getDepth_1_VO1() {
        return (ViewObjectImpl)findViewObject("Depth_1_VO1");
    }

    /**
     * Container's getter for ViewLink1_1.
     * @return ViewLink1_1
     */
    public ViewLinkImpl getViewLink1_1() {
        return (ViewLinkImpl)findViewLink("ViewLink1_1");
    }

    /**
     * Container's getter for Depth_2_VO1.
     * @return Depth_2_VO1
     */
    public ViewObjectImpl getDepth_2_VO1() {
        return (ViewObjectImpl)findViewObject("Depth_2_VO1");
    }

    /**
     * Container's getter for ViewLink2_1.
     * @return ViewLink2_1
     */
    public ViewLinkImpl getViewLink2_1() {
        return (ViewLinkImpl)findViewLink("ViewLink2_1");
    }

    /**
     * Container's getter for Depth_3_VO1.
     * @return Depth_3_VO1
     */
    public ViewObjectImpl getDepth_3_VO1() {
        return (ViewObjectImpl)findViewObject("Depth_3_VO1");
    }

    /**
     * Container's getter for ViewLink3_1.
     * @return ViewLink3_1
     */
    public ViewLinkImpl getViewLink3_1() {
        return (ViewLinkImpl)findViewLink("ViewLink3_1");
    }

    /**
     * Container's getter for Depth_4_VO1.
     * @return Depth_4_VO1
     */
    public ViewObjectImpl getDepth_4_VO1() {
        return (ViewObjectImpl)findViewObject("Depth_4_VO1");
    }

    /**
     * Container's getter for ViewLink4_1.
     * @return ViewLink4_1
     */
    public ViewLinkImpl getViewLink4_1() {
        return (ViewLinkImpl)findViewLink("ViewLink4_1");
    }

    /**
     * Container's getter for Depth_5_VO1.
     * @return Depth_5_VO1
     */
    public ViewObjectImpl getDepth_5_VO1() {
        return (ViewObjectImpl)findViewObject("Depth_5_VO1");
    }

    /**
     * Container's getter for ViewLink5_1.
     * @return ViewLink5_1
     */
    public ViewLinkImpl getViewLink5_1() {
        return (ViewLinkImpl)findViewLink("ViewLink5_1");
    }

    /**
     * Container's getter for Depth_6_VO1.
     * @return Depth_6_VO1
     */
    public ViewObjectImpl getDepth_6_VO1() {
        return (ViewObjectImpl)findViewObject("Depth_6_VO1");
    }

    /**
     * Container's getter for ViewLink6_1.
     * @return ViewLink6_1
     */
    public ViewLinkImpl getViewLink6_1() {
        return (ViewLinkImpl)findViewLink("ViewLink6_1");
    }
}
