package sz.susan.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 19 14:34:36 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NodeVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public NodeVOImpl() {
    }

    /**
     * Returns the variable value for serviceID.
     * @return variable value for serviceID
     */
    public Integer getserviceID() {
        return (Integer)ensureVariableManager().getVariableValue("serviceID");
    }

    /**
     * Sets <code>value</code> for variable serviceID.
     * @param value value to bind as serviceID
     */
    public void setserviceID(Integer value) {
        ensureVariableManager().setVariableValue("serviceID", value);
    }
}
