package sz.susan.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 19 16:51:03 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ServiceVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ServiceVOImpl() {
    }

    /**
     * Returns the variable value for ServeID.
     * @return variable value for ServeID
     */
    public Integer getServeID() {
        return (Integer)ensureVariableManager().getVariableValue("ServeID");
    }

    /**
     * Sets <code>value</code> for variable ServeID.
     * @param value value to bind as ServeID
     */
    public void setServeID(Integer value) {
        ensureVariableManager().setVariableValue("ServeID", value);
    }
}
