package sz.susan.VO;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 19 16:54:40 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class trancationVORowImpl extends ViewRowImpl {


    public static final int ENTITY_TRANSACTION = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Id {
            public Object get(trancationVORowImpl obj) {
                return obj.getId();
            }

            public void put(trancationVORowImpl obj, Object value) {
                obj.setId((Integer)value);
            }
        }
        ,
        Name {
            public Object get(trancationVORowImpl obj) {
                return obj.getName();
            }

            public void put(trancationVORowImpl obj, Object value) {
                obj.setName((String)value);
            }
        }
        ,
        Successflag {
            public Object get(trancationVORowImpl obj) {
                return obj.getSuccessflag();
            }

            public void put(trancationVORowImpl obj, Object value) {
                obj.setSuccessflag((String)value);
            }
        }
        ,
        Description {
            public Object get(trancationVORowImpl obj) {
                return obj.getDescription();
            }

            public void put(trancationVORowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        Transactiondate {
            public Object get(trancationVORowImpl obj) {
                return obj.getTransactiondate();
            }

            public void put(trancationVORowImpl obj, Object value) {
                obj.setTransactiondate((Timestamp)value);
            }
        }
        ,
        Attribute10 {
            public Object get(trancationVORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(trancationVORowImpl obj, Object value) {
                obj.setAttribute10((Integer)value);
            }
        }
        ,
        Attribute6 {
            public Object get(trancationVORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(trancationVORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(trancationVORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(trancationVORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(trancationVORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(trancationVORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(trancationVORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(trancationVORowImpl obj, Object value) {
                obj.setAttribute9((Integer)value);
            }
        }
        ,
        TotalTime {
            public Object get(trancationVORowImpl obj) {
                return obj.getTotalTime();
            }

            public void put(trancationVORowImpl obj, Object value) {
                obj.setTotalTime((Integer)value);
            }
        }
        ,
        ExceptTotalTime {
            public Object get(trancationVORowImpl obj) {
                return obj.getExceptTotalTime();
            }

            public void put(trancationVORowImpl obj, Object value) {
                obj.setExceptTotalTime((Integer)value);
            }
        }
        ,
        NodeVO1 {
            public Object get(trancationVORowImpl obj) {
                return obj.getNodeVO1();
            }

            public void put(trancationVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Depth_1_VO {
            public Object get(trancationVORowImpl obj) {
                return obj.getDepth_1_VO();
            }

            public void put(trancationVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(trancationVORowImpl object);

        public abstract void put(trancationVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int SUCCESSFLAG = AttributesEnum.Successflag.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int TRANSACTIONDATE = AttributesEnum.Transactiondate.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int TOTALTIME = AttributesEnum.TotalTime.index();
    public static final int EXCEPTTOTALTIME = AttributesEnum.ExceptTotalTime.index();
    public static final int NODEVO1 = AttributesEnum.NodeVO1.index();
    public static final int DEPTH_1_VO = AttributesEnum.Depth_1_VO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public trancationVORowImpl() {
    }

    /**
     * Gets Transaction entity object.
     * @return the Transaction
     */
    public EntityImpl getTransaction() {
        return (EntityImpl)getEntity(ENTITY_TRANSACTION);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public Integer getId() {
        return (Integer) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(Integer value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for NAME using the alias name Name.
     * @return the NAME
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as attribute value for NAME using the alias name Name.
     * @param value value to set the NAME
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for SUCCESSFLAG using the alias name Successflag.
     * @return the SUCCESSFLAG
     */
    public String getSuccessflag() {
        return (String) getAttributeInternal(SUCCESSFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for SUCCESSFLAG using the alias name Successflag.
     * @param value value to set the SUCCESSFLAG
     */
    public void setSuccessflag(String value) {
        setAttributeInternal(SUCCESSFLAG, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for TRANSACTIONDATE using the alias name Transactiondate.
     * @return the TRANSACTIONDATE
     */
    public Timestamp getTransactiondate() {
        return (Timestamp) getAttributeInternal(TRANSACTIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSACTIONDATE using the alias name Transactiondate.
     * @param value value to set the TRANSACTIONDATE
     */
    public void setTransactiondate(Timestamp value) {
        setAttributeInternal(TRANSACTIONDATE, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE_10 using the alias name Attribute10.
     * @return the ATTRIBUTE_10
     */
    public Integer getAttribute10() {
        return (Integer) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE_10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE_10
     */
    public void setAttribute10(Integer value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE_6 using the alias name Attribute6.
     * @return the ATTRIBUTE_6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE_6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE_6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE_7 using the alias name Attribute7.
     * @return the ATTRIBUTE_7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE_7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE_7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE_8 using the alias name Attribute8.
     * @return the ATTRIBUTE_8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE_8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE_8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE_9 using the alias name Attribute9.
     * @return the ATTRIBUTE_9
     */
    public Integer getAttribute9() {
        return (Integer) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE_9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE_9
     */
    public void setAttribute9(Integer value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalTime.
     * @return the TotalTime
     */
    public Integer getTotalTime() {
        return (Integer) getAttributeInternal(TOTALTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalTime.
     * @param value value to set the  TotalTime
     */
    public void setTotalTime(Integer value) {
        setAttributeInternal(TOTALTIME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ExceptTotalTime.
     * @return the ExceptTotalTime
     */
    public Integer getExceptTotalTime() {
        return (Integer) getAttributeInternal(EXCEPTTOTALTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ExceptTotalTime.
     * @param value value to set the  ExceptTotalTime
     */
    public void setExceptTotalTime(Integer value) {
        setAttributeInternal(EXCEPTTOTALTIME, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link NodeVO1.
     */
    public RowIterator getNodeVO1() {
        return (RowIterator)getAttributeInternal(NODEVO1);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link Depth_1_VO.
     */
    public RowIterator getDepth_1_VO() {
        return (RowIterator)getAttributeInternal(DEPTH_1_VO);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
