package sz.susan.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 19 16:54:41 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class trancationVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public trancationVOImpl() {
    }

    /**
     * Returns the variable value for tName.
     * @return variable value for tName
     */
    public String gettName() {
        return (String)ensureVariableManager().getVariableValue("tName");
    }

    /**
     * Sets <code>value</code> for variable tName.
     * @param value value to bind as tName
     */
    public void settName(String value) {
        ensureVariableManager().setVariableValue("tName", value);
    }

    /**
     * Returns the bind variable value for tId.
     * @return bind variable value for tId
     */
    public Integer gettId() {
        return (Integer)getNamedWhereClauseParam("tId");
    }

    /**
     * Sets <code>value</code> for bind variable tId.
     * @param value value to bind as tId
     */
    public void settId(Integer value) {
        setNamedWhereClauseParam("tId", value);
    }
}
